title: QianZhang's Homepage
page-top-title: Qian Zhang (张迁)
# top-section-bg-text: Be what you wanna be
email: Zhangqian@jsou.edu.cn
copyright-text: '&copy; Qian Zhang 2023-2025. All Rights Reserved.'
