title: Zhang Qian's Homepage
page-top-title: Zhang Qian (张迁)
top-section-bg-text: Keep on going never give up.
email: Zhangqian@jsou.edu.cn
copyright-text: '&copy; Zhang Qian 2023-2025. All Rights Reserved.'
